Repository chingu-voyages/V53-tier3-team-38, pull requests merged in 2025-01, with the labels that each got.

#21 Update: add team credentials to README.md
  README.md
Labels: documentation

#20 15 initial vite project
  client/.gitignore
  client/.prettier.json
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/comingSoon/ComingSoon.css
  client/src/components/comingSoon/ComingSoon.tsx
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: fe

#30 feat: add supabase setup
  .env.sample
  .gitignore
  .prettier.json
  client/README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/comingSoon/ComingSoon.css
  src/components/comingSoon/ComingSoon.tsx
  src/database.types.ts
  src/main.tsx
  src/supabase-client.ts
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: be
